In [1]:
!pip install flair

     |████████████████████████████████| 450kB 7.8MB/s 
     |████████████████████████████████| 71kB 8.3MB/s 
     |████████████████████████████████| 19.7MB 1.2MB/s 
     |████████████████████████████████| 798kB 59.6MB/s 
     |████████████████████████████████| 1.3MB 41.2MB/s 
     |████████████████████████████████| 1.1MB 21.1MB/s 
     |████████████████████████████████| 983kB 44.7MB/s 
     |████████████████████████████████| 2.9MB 45.5MB/s 
     |████████████████████████████████| 890kB 42.3MB/s 
  Created wheel for ftfy: filename=ftfy-5.8-cp36-none-any.whl size=45613 sha256=3f72e603ee1559ee8fcfd34eec9e9c74f95e87cd306839944e156e6c417290a0
  Stored in directory: /root/.cache/pip/wheels/ba/c0/ef/f28c4da5ac84a4e06ac256ca9182fc34fa57fefffdbc68425b
  Created wheel for mpld3: filename=mpld3-0.3-cp36-none-any.whl size=116679 sha256=a0cac9c20e65d86f89324360e64ade4082b9d9c342be6d86c8ef408295ec686b
  Stored in directory: /root/.cache/pip/wheels/c0/47/fb/8a64f89aecfe0059830479308ad42d62e898a3e3cef

In [2]:
import numpy as np
from flair.embeddings import WordEmbeddings
from flair.embeddings import TransformerWordEmbeddings
from flair.data import Sentence
from scipy.spatial import distance

# Glove Embeddings Example

In [3]:
glove_embedding = WordEmbeddings('glove')

2020-12-15 12:17:49,755 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim.vectors.npy not found in cache, downloading to /tmp/tmp7l2f7t_x


100%|██████████| 160000128/160000128 [00:33<00:00, 4809899.11B/s]

2020-12-15 12:18:23,516 copying /tmp/tmp7l2f7t_x to cache at /root/.flair/embeddings/glove.gensim.vectors.npy


2020-12-15 12:18:23,765 removing temp file /tmp/tmp7l2f7t_x
2020-12-15 12:18:24,610 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim not found in cache, downloading to /tmp/tmpgx8p8xh7


100%|██████████| 21494764/21494764 [00:02<00:00, 7606372.07B/s]

2020-12-15 12:18:27,936 copying /tmp/tmpgx8p8xh7 to cache at /root/.flair/embeddings/glove.gensim
2020-12-15 12:18:27,959 removing temp file /tmp/tmpgx8p8xh7


## Sentence 1

In [4]:
sentence_1 = Sentence('apple released iphone 12 pro max in 2020')

In [5]:
glove_embedding.embed(sentence_1)

[Sentence: "apple released iphone 12 pro max in 2020"   [− Tokens: 8]]

In [6]:
for token in sentence_1:
    print(token)
    print(token.embedding)
    print("\n")

Token: 1 apple
tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,

In [7]:
sentence_1[0]

Token: 1 apple

In [10]:
sentence_1[0].embedding

tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,  1.3431,  0.34

In [11]:
sentence_1[0].embedding.shape

torch.Size([100])

## Sentence 2

In [12]:
sentence_2 = Sentence('an apple a day keeps the doctor away')

In [13]:
glove_embedding.embed(sentence_2)

[Sentence: "an apple a day keeps the doctor away"   [− Tokens: 8]]

In [14]:
for token in sentence_2:
    print(token)
    print(token.embedding)
    print("\n")

Token: 1 an
tensor([-0.4214, -0.1880,  0.4624, -0.1761,  0.3621,  0.3670,  0.2792,  0.1463,
        -0.0542,  0.4583,  0.0654, -0.3372,  0.0675, -0.3632,  0.5030, -0.0104,
         0.7283, -0.1756, -0.3400,  0.0729,  0.6448, -0.2391,  0.3838,  0.1386,
         1.0994, -0.2488, -0.1508, -0.4874, -0.2304,  0.0648, -0.7018,  0.8265,
         0.0613,  0.1853, -0.3016, -0.0222,  0.3430,  0.8033,  0.1714,  0.1546,
        -0.5076,  0.3957,  0.0543, -0.5308,  0.4825,  0.0862,  0.5958, -0.2238,
        -0.3955, -0.7304, -0.1028, -0.3917,  1.2290,  1.2129, -1.0365, -3.4971,
         0.1092, -1.0084,  1.9998,  0.7964,  0.3881,  0.4375,  0.0852,  0.3855,
         0.6199, -1.0320,  0.7012, -0.2246,  0.0794,  0.0913, -0.2120, -0.5543,
        -0.0534, -0.8020,  0.4680, -0.0501, -0.5742, -0.0848, -1.7227, -0.9429,
         0.9867,  0.3121, -0.3774,  0.0687, -0.7784, -0.2849,  0.8105,  0.4660,
        -0.1186, -0.9341,  0.3372,  0.0379, -0.1827, -0.0199,  0.2049, -0.4772,
        -0.4925, -0.5652,  0

In [15]:
sentence_2[1]

Token: 2 apple

In [16]:
sentence_2[1].embedding

tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,  1.3431,  0.34

In [17]:
sentence_2[1].embedding.shape

torch.Size([100])

## Glove Distance between the same word

In [18]:
glove_dst = distance.euclidean(np.array(sentence_1[0].embedding), 
                               np.array(sentence_2[1].embedding))

In [19]:
print("Distance between apple embeddings for Glove = {}".format(glove_dst))

Distance between apple embeddings for Glove = 0.0


# Bert Embeddings

In [20]:
bert_embedding = TransformerWordEmbeddings('bert-base-multilingual-cased')

In [21]:
bert_embedding.embed(sentence_1)
for token in sentence_1:
    print(token)
    print(token.embedding)

Token: 1 apple
tensor([-0.5985, -0.4632,  0.1300,  ...,  1.4355,  0.0781,  0.2832])
Token: 2 released
tensor([-0.0451, -0.7260,  0.6271,  ...,  0.8646,  0.4700,  0.4862])
Token: 3 iphone
tensor([-0.3609, -0.5975,  0.5235,  ...,  0.8601,  0.1087, -0.7263])
Token: 4 12
tensor([ 0.0730,  0.1813,  0.0204,  ...,  1.0590,  0.4350, -0.1114])
Token: 5 pro
tensor([-0.2332,  0.1988, -0.2101,  ...,  1.8614,  0.7496, -0.2961])
Token: 6 max
tensor([ 0.3356,  0.1247,  0.2099,  ...,  1.3470, -0.0816,  0.4086])
Token: 7 in
tensor([ 0.0857, -0.2220,  0.1657,  ...,  1.4064, -0.2576, -0.0673])
Token: 8 2020
tensor([-0.1241,  0.3447,  0.9852,  ...,  0.8098,  1.0564, -0.2190])


In [22]:
sentence_1[0]

Token: 1 apple

In [23]:
sentence_1[0].embedding

tensor([-0.5985, -0.4632,  0.1300,  ...,  1.4355,  0.0781,  0.2832])

In [24]:
sentence_1[0].embedding.shape

torch.Size([3172])

In [25]:
bert_embedding.embed(sentence_2)

for token in sentence_2:
    print(token)
    print(token.embedding)

Token: 1 an
tensor([-0.4214, -0.1880,  0.4624,  ...,  1.2605,  0.8692,  0.1740])
Token: 2 apple
tensor([-0.5985, -0.4632,  0.1300,  ...,  1.8314,  1.0177,  0.2707])
Token: 3 a
tensor([-0.2709,  0.0440, -0.0203,  ...,  0.8354, -0.3497,  0.5959])
Token: 4 day
tensor([-0.3669,  0.4154,  0.1348,  ...,  0.9259, -0.0530,  0.1594])
Token: 5 keeps
tensor([-0.2821,  0.0814,  1.0041,  ...,  0.1253,  0.6754, -0.1647])
Token: 6 the
tensor([-0.0382, -0.2449,  0.7281,  ..., -0.1876, -0.3076,  0.5679])
Token: 7 doctor
tensor([ 0.0432, -0.4753,  0.1581,  ...,  0.7838,  0.3551,  0.3403])
Token: 8 away
tensor([-0.1038, -0.0148,  0.5993,  ...,  1.2423,  0.4363,  0.1388])


In [26]:
sentence_2[1]

Token: 2 apple

In [27]:
sentence_2[1].embedding

tensor([-0.5985, -0.4632,  0.1300,  ...,  1.8314,  1.0177,  0.2707])

In [28]:
sentence_2[1].embedding.shape

torch.Size([3172])

In [29]:
bert_dst = distance.euclidean(np.array(sentence_1[0].embedding), 
                               np.array(sentence_2[1].embedding))

In [30]:
print("Distance between apple embeddings for Glove = {}".format(bert_dst))

Distance between apple embeddings for Glove = 44.70344924926758
